services:
  azat:
    container_name: azat
    build: ./src
    volumes:
      - ./src/:/usr/src/app/
    expose:
      - 5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=azatnv
      - POSTGRES_PASSWORD=azatnv
      - POSTGRES_DB=azatnv_db

volumes:
  postgres_data: